version: '3.8'
services:
  postgres:
    image: postgres:13.6
    container_name: user-segmenter-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./user-segmenter-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 7s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]
  user-segmenter:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URI=${POSTGRES_DSN}
      - RUN_ADDRESS=${SEGMENTER_SERVER_ADDRESS}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./reports:/user-segmenter/reports
