basePath: /
definitions:
  github_com_PoorMercymain_user-segmenter_internal_domain.Slug:
    properties:
      percent:
        example: 10
        type: integer
      slug:
        example: SEGMENT_NAME
        type: string
    type: object
  github_com_PoorMercymain_user-segmenter_internal_domain.SlugNoPercent:
    properties:
      slug:
        example: SEGMENT_NAME
        type: string
    type: object
  github_com_PoorMercymain_user-segmenter_internal_domain.UserUpdate:
    properties:
      slugs_to_add:
        example:
        - SEGMENT_NAME
        items:
          type: string
        type: array
      slugs_to_delete:
        example:
        - SEGMENT_NAME
        items:
          type: string
        type: array
      ttl:
        example:
        - "2023-09-30T20:19:05+03:00"
        items:
          type: string
        type: array
      user_id:
        example: "1"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис динамического сегментирования пользователей
  title: UserSegmenter API
  version: "1.0"
paths:
  /api/reports/{filename}:
    get:
      description: Запрос для получения отчета по истории сегментов пользователя в
        формате csv
      parameters:
      - description: report filename
        example: report12345.csv
        in: path
        name: filename
        required: true
        type: string
      produces:
      - text/csv
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Запрос чтения отчета по истории сегментов пользователя
      tags:
      - Reports
  /api/segment:
    delete:
      consumes:
      - application/json
      description: Запрос для удаления сегмента из списка существующих сегментов по
        уникальному названию
      parameters:
      - description: segment info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_PoorMercymain_user-segmenter_internal_domain.SlugNoPercent'
      responses:
        "202":
          description: Accepted
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Запрос для удаления сегмента
      tags:
      - Segments
    post:
      consumes:
      - application/json
      description: Запрос для создания сегмента по уникальному названию
      parameters:
      - description: segment info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_PoorMercymain_user-segmenter_internal_domain.Slug'
      responses:
        "200":
          description: OK
        "202":
          description: Accepted
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Запрос для создания нового сегмента
      tags:
      - Segments
  /api/user:
    post:
      consumes:
      - application/json
      description: Запрос для обновления списка сегментов пользователя
      parameters:
      - description: user segment info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_PoorMercymain_user-segmenter_internal_domain.UserUpdate'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Запрос обновления сегментов пользователя
      tags:
      - Users
  /api/user-history/{id}:
    get:
      description: Запрос для создания отчета по истории сегментов пользователя в
        формате csv
      parameters:
      - description: user id
        example: "1"
        in: path
        name: id
        required: true
        type: string
      - description: start date
        example: 2023-9
        in: query
        name: start
        type: string
      - description: end date
        example: 2023-9
        in: query
        name: end
        type: string
      - description: exact date
        example: 2023-9
        in: query
        name: exact
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Запрос формирования отчета по истории сегментов пользователя
      tags:
      - Reports
  /api/user/{id}:
    get:
      description: Запрос для получения списка сегментов пользователя
      parameters:
      - description: user id
        example: "1"
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Запрос чтения сегментов пользователя
      tags:
      - Users
schemes:
- http
swagger: "2.0"
tags:
- description: Группа запросов для управления списком существующих сегментов
  name: Segments
- description: Группа запросов для управления сегментами пользователя
  name: Users
- description: Группа запросов для работы с отчетами по истории сегментов пользователя
  name: Reports
